### ISSUE TITLE
Post Issue

### ISSUE THREAD

**Issue by desstannoz** [mnkgrover08/whatsapp_automation#3]
AttributeError: 'WhatsAppNewContactListener' object has no attribute 'apilog'

**Comment by mnkgrover08** [comment]
This Error arises when we don't have log files available in /var/log directory.
Execute following commands prior to starting the project

sudo mkdir -p /var/www/whatsapp_api
sudo chmod -R 777 /var/www/whatsapp_api
sudo touch /var/www/whatsapp_single_worker.log
sudo chmod -R 777 /var/www/whatsapp_single_worker.log
sudo touch /var/www/whatsapp_single_consumer.log
sudo chmod -R 777 /var/www/whatsapp_single_consumer.log
sudo touch /var/log/whatsapp_api/api.log
sudo chmod -R 777 /var/log/whatsapp_api/api.log

Above commands will create the required log files.
