### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by lddd** [mnkgrover08/whatsapp_automation#9]
Great work, got one question.

Lets say i have more than 256 contacts for one "Number/Emulator/Device" i would like to send messages to.

Would it be possible to have some kind of automation method here creating broadcast lists for the emulated device contacts splitted by 256 each list?

Because of whatsapp internal limitation of 256 contacts per broadcast list. 

Plus a API method to send to one or multiple broadcast lists after that. 

Like i understand the existing "broadcast" it will simply do a bulk send but send one by one instead of sending to many contacts at once right?

**Comment by mnkgrover08** [comment]
Roman

as of now handling of broadcast list for more than 256 contacts is not
implemented.
But the idea behind that would be creating different chunks of broadcast
list, each comprising of 256.
eg. lets say you need to broadcast message to 500 contacts then you need to
have 2 broadcast lists.
1st - 256 recipients
2nd - 244 recipients

so in this you will hit the api with 500 recipients as input inside the api
handling controller 500 recipients will be breakdown into 2 lists with
random name. then each will be pushed to queue separately.

Regards
Mayank

**Comment by lddd** [comment]
Hi,

Yes. But how to opt-out a single number on request? Can we have a listener constantly waiting for commands like "stop" and "start". So if a number sends "start" this number will be added to broadcast recipients (if non existing) or reactivated. If sending "stop" such number would be removed from broadcast recipients?

I would be highly interested in some API providing newsletter similar functionality in case of whatsapp subscribers.

So your approach here looked promising to me. 

Let me know if you are maybe available to freelance work to have further custom functionality here added to this API.

best regards,
Roman
